# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-plugin"

[[constraint]]
  branch = "support-custom-snapshots"
  name = "github.com/heptio/ark"
  source = "https://github.com/ncdc/ark.git"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"